name: Deploy Site

on:
  push:
    branches:
      - main
    paths:
      - 'documents/**'
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python (uv)
        uses: astral-sh/setup-uv@v5

      - name: Deploy to GitHub Pages
        run: |
          cd documents
          uv run mkdocs gh-deploy --config-file mkdocs.yml --force
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
